[custom]

;˙☆`·.·˙˙`··˙˙`··˙☆`·.·˙˙`··˙☆˙

ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
ruleset=🎯 全球直连,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 全球直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
ruleset=🥤 节点选择,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.yaml,28800
ruleset=🥤 节点选择,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
ruleset=🎯 全球直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🌐 社交媒体,[]GEOSITE,category-communication
ruleset=🌐 社交媒体,[]GEOSITE,category-social-media-!cn
ruleset=📖 人工智能,[]GEOSITE,openai
ruleset=📖 人工智能,[]GEOSITE,category-ai-!cn
ruleset=🌐 社交媒体,[]GEOSITE,github
ruleset=🍪 谷歌服务,[]GEOSITE,category-speedtest
ruleset=🎮 游戏平台,[]GEOSITE,steam
ruleset=🍪 谷歌服务,[]GEOSITE,youtube
ruleset=🎞 影音媒体,[]GEOSITE,apple-tvplus
ruleset=Ⓜ️ 系统服务,[]GEOSITE,apple
ruleset=Ⓜ️ 系统服务,[]GEOSITE,microsoft
ruleset=🍪 谷歌服务,[]GEOSITE,googlefcm
ruleset=🍪 谷歌服务,[]GEOSITE,google
ruleset=🎞 影音媒体,[]GEOSITE,tiktok
ruleset=📼 奈飞视频,[]GEOSITE,netflix
ruleset=🎞 影音媒体,[]GEOSITE,disney
ruleset=🎞 影音媒体,[]GEOSITE,hbo
ruleset=🎞 影音媒体,[]GEOSITE,primevideo
ruleset=🎞 影音媒体,[]GEOSITE,category-emby
ruleset=🎞 影音媒体,[]GEOSITE,spotify
ruleset=📺 巴哈姆特,[]GEOSITE,bahamut
ruleset=📺 哔哩哔哩,[]GEOSITE,bilibili
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=🌐 社交媒体,[]GEOSITE,category-entertainment
ruleset=🌐 社交媒体,[]GEOSITE,category-ecommerce
ruleset=🥤 节点选择,[]GEOSITE,gfw
ruleset=🌐 社交媒体,[]GEOIP,telegram,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,twitter,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,facebook,no-resolve
ruleset=🍪 谷歌服务,[]GEOIP,google,no-resolve
ruleset=📼 奈飞视频,[]GEOIP,netflix,no-resolve
ruleset=🎯 全球直连,[]GEOSITE,cn
ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve
ruleset=🔀 非标端口,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
ruleset=🐟 漏网之鱼,[]FINAL

;˙☆`·.·˙˙`··˙˙`··˙☆`·.·˙˙`··˙☆˙

custom_proxy_group=✨ 自动选择`url-test`.*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🥤 节点选择`select`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点`.*
custom_proxy_group=💗 手动选择`select`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点`.*
custom_proxy_group=🎞 影音媒体`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=🌐 社交媒体`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=🍪 谷歌服务`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=📼 奈飞视频`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=📺 哔哩哔哩`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=📺 巴哈姆特`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=Ⓜ️ 系统服务`select`[]🎯 全球直连`[]🥤 节点选择`[]💗 手动选择`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🥤 节点选择`[]💗 手动选择`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=📖 人工智能`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=🐟 漏网之鱼`select`[]🥤 节点选择`[]💗 手动选择`[]🎯 全球直连`[]✨ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 狮城节点`[]🇪🇺 欧洲节点
custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连
custom_proxy_group=🇭🇰 香港节点`select`(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`select`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`select`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`select`(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`select`(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧洲节点`select`(欧|德国|德|柏林|法兰克福|法|法国|巴黎|荷|荷兰|阿姆斯特丹|英|英国|伦敦|意|意大利|米兰|瑞|瑞士|苏黎世|西班牙|马德里|瑞典|丹麦|芬兰|挪威|波兰|比利时|捷克|奥地利|EU|Europe|DE|UK)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🥤 节点选择`[]💗 手动选择`[]✨ 自动选择

;˙☆`·.·˙˙`··˙˙`··˙☆`·.·˙˙`··˙☆˙

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/Colsine/Scripts/main/Rules/Clash/Extension.yaml
